Full update of postinst, postrm, prerm scripts. Remove obsolete preinst script and chrony.conf.md5sum file.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,96 +1,74 @@
 #!/bin/sh
+# postinst script for chrony
+#
+# see: dh_installdeb(1)
+
 set -e
-# postinst for Chrony John Hasler jhasler@debian.org 2000-2006
-# Any possessor of a copy of this program may treat it as if it
-# were in the public domain.  I waive all rights.
 
-#install-info --quiet --description="Set your clock from the Net" \
-#	     --section General "General Commands"
-#             /usr/share/info/chrony.info
+# targets: configure|abort-upgrade|abort-remove|abort-deconfigure
 
-if [ -x /usr/bin/update-menus ] ; then 
-    update-menus 
-fi
+case "$1" in
+    configure)
 
-update-rc.d chrony defaults 83 >/dev/null
+        cp /usr/share/chrony/chrony.conf /etc/chrony/chrony.conf.new
+        MAILUTC=""
+        # look for real-time clock
+        . /etc/default/rcS
 
-cp /usr/share/chrony/chrony.conf /etc/chrony/chrony.conf.new
+        case "$UTC" in
+          no|"")
+            echo "# rtconutc" >> /etc/chrony/chrony.conf.new
+          ;;
+          yes)
+            echo "rtconutc" >> /etc/chrony/chrony.conf.new
+          ;;
+          *)
+            echo "# rtconutc" >> /etc/chrony/chrony.conf.new
+            MAILUTC="Chrony do not know how your clock is set: assuming local time.
+If this is not correct edit /etc/chrony/chrony.conf. The comments
+explain what to do."
+          ;;
+        esac
 
-# Fix up chrony.conf.new.
-. /etc/default/rcS
+        if [ -z "$2" ]
+        then
+            # As this is a new install, generate a key.
+            # Remove any keyfile left by a failed install.
+            rm -rf /etc/chrony/chrony.keys
+            KEYFILE=`tempfile -m 640 -n /etc/chrony/chrony.keys`
+            PASSWORD=`head -c 8 /dev/urandom | tr '\0-\377' 'a-zA-Z0-9a-zA-Z0-9a-zA-Z0-9a-zA-Z0-9@@@@####'`
+            echo "1 $PASSWORD" > $KEYFILE
+            MAILPASSWORD="The password for chronyc is in $KEYFILE."
 
-case "$UTC" in
-    no|"") echo "# rtconutc" >> /etc/chrony/chrony.conf.new
-	MAILUTC="Chrony has been configured to assume that your real-time clock is on local time.
-If this is not correct edit /etc/chrony/chrony.conf.  The comments explain
-what to do."
-	;;
-    yes)   echo "rtconutc" >> /etc/chrony/chrony.conf.new
-	MAILUTC="Chrony has been configured to assume that your real-time clock is on UTC time.
-If this is not correct edit /etc/chrony/chrony.conf.  The comments explain
-what to do."
-	;;
-    *)     echo "# Can't tell how your clock is set: assuming local time." >> /etc/chrony/chrony.conf.new
-	MAILUTC="Can't tell how your clock is set: assuming local time.
-If this is not correct edit /etc/chrony/chrony.conf.  The comments explain
-what to do."
-	;;
+            if [ `echo $MAILUTC | wc -m` -gt 10 ]
+            then
+                # And tell root about the rtc setting
+                if `which mail >/dev/null`
+                then
+                 echo "$MAILUTC" | mail -s "Chrony" root
+                fi
+            fi
+        fi
+
+        if `which ucf >/dev/null`
+        then
+          ucf /etc/chrony/chrony.conf.new /etc/chrony/chrony.conf
+          rm /etc/chrony/chrony.conf.new
+        fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
 
-if [ -z "$2" ] ; then
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
-# As this a new install generate a key.  Remove any keyfile left by a failed install.
-    rm -rf /etc/chrony/chrony.keys
-    KEYFILE=`tempfile -m 640 -n /etc/chrony/chrony.keys`
-    PASSWORD=`head -c 8 /dev/urandom | tr '\0-\377' 'a-zA-Z0-9a-zA-Z0-9a-zA-Z0-9a-zA-Z0-9@@@@####'`
-    echo "1 $PASSWORD" > $KEYFILE
-    MAILPASSWORD="The password for chronyc is in $KEYFILE."
+#DEBHELPER#
 
-# And tell root about the key and the rtc setting.    
-    if `which /usr/bin/mail > /dev/null`; then
-	/usr/bin/mail -s "Chrony" root <<EOF
-
-$MAILPASSWORD
-
-$MAILUTC
-
-In the chrony.conf included in this package:
-
-Chrony has been configured on the assumption that you are using either a
-dialup connection or a PPPoE DSL connection.  It will be brought online
-when PPP comes up and offline when it goes down.  Code in
-/etc/init.d/chrony attempts to determine whether the network is up or down
-at boot time and sets chronyd on or off line accordingly.  If this is not
-correct you should edit /etc/chrony/chrony.conf.  The comments explain what
-to do.  For more information on configuring Chrony use the command 'info
-chrony'.
-
-You can also change the default time servers in  /etc/chrony/chrony.conf.
-
-Updating of the real-time clock has been disabled because some systems that use
-either the genrtc driver or have HPET hardware clocks have problems.  To
-enable real-time clock updating edit /etc/chrony/chrony.conf.  The
-comments explain what to do.
-
-EOF
-    fi
-
-else
-    
-# If we are upgrading from an old version retrieve the files saved by the preinst.
-# If we are upgrading from a recent version no need to do anything.
-    
-    if dpkg --compare-versions "$2" lt-nl 1.21-3 ; then
-	if [ -f /etc/chrony/chrony.keys."$2" ]; then
-	    mv /etc/chrony/chrony.keys."$2" /etc/chrony/chrony.keys
-	fi
-	if [ -f /etc/chrony/chrony.conf."$2" ]; then
-	    mv /etc/chrony/chrony.conf."$2" /etc/chrony/chrony.conf
-	fi
-    fi
-fi
-ucf --sum-file /usr/share/chrony/chrony.conf.md5sum /etc/chrony/chrony.conf.new /etc/chrony/chrony.conf
-rm /etc/chrony/chrony.conf.new
-
-invoke-rc.d chrony start
 exit 0
diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -1,27 +1,38 @@
 #!/bin/sh
-set -e
-# postrm for chrony John Hasler 1998-2006
-# Any possessor of a copy of this program may treat it as if it
-# were in the public domain.  I waive all rights.
-rm -f /var/lib/chrony/*
-if [ -x update-menus ] ; then 
-	update-menus
-fi
+# postrm script for chrony
+#
+# see: dh_installdeb(1)
 
-if [ "$1" = "purge" ] ; then
-    rm -rf /etc/chrony/chrony.conf
-    if which ucf >/dev/null; then
-	ucf --purge /etc/chrony/chrony.conf
-    fi
-    if which ucfr >/dev/null; then
-	ucfr --purge chrony /etc/chrony/chrony.conf
-    fi
-    rm -rf /var/lib/chrony
-    rm -rf /usr/share/chrony
-    rm -rf /var/log/chrony
-    rm -rf /etc/cron.weekly/chrony
-    rm -rf /etc/ppp/ip-up.d/chrony
-    rm -rf /etc/ppp/ip-down.d/chrony
-    rm -rf /etc/chrony
-    update-rc.d chrony remove >/dev/null
-fi
+set -e
+
+# targets: purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear
+
+case "$1" in
+    purge)
+        rm -f /var/lib/chrony/*
+        rm -f /etc/chrony/chrony.conf
+        if `which ucf >/dev/null`
+        then
+            ucf --purge /etc/chrony/chrony.conf
+        fi
+        rm -rf /etc/chrony
+        rm -rf /var/lib/chrony
+        rm -rf /var/log/chrony
+    ;;
+
+    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+        rm -f /var/lib/chrony/*
+    ;;
+
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -1,9 +1,28 @@
 #!/bin/sh
+# prerm script for chrony
+#
+# see: dh_installdeb(1)
+
 set -e
-# Automatically added by dh_installinit
-# install-info --quiet --remove /usr/share/info/chrony.info.gz
-invoke-rc.d chrony stop
-if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/chrony ]; then
-     rm -f /usr/doc/chrony
-fi
-# End automatically added section
+
+# targets: remove|upgrade|deconfigure|failed-upgrade
+
+case "$1" in
+    remove|upgrade|deconfigure)
+    ;;
+
+    failed-upgrade)
+    ;;
+
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
